Repository flexpa/sero, pull requests merged in 2021-08, with the labels that each got.

#62 Updated dependencies
  example/goodrx-cds-price-comparison/README.md
  package-lock.json
  package.json
Labels: chore

#65 Support searchType operation in Client
  package.json
  src/cds-hooks/index.ts
  src/client/index.test.ts
  src/client/index.ts
  src/index.ts
Labels: enhancement

#66 Query support for SearchType and Reference support for Read
  src/client/index.test.ts
  src/client/index.ts
Labels: enhancement

#70 CDS Hooks API guide example 3 code
  example/cds-hooks-api-guide/package-lock.json
  example/cds-hooks-api-guide/package.json
  example/cds-hooks-api-guide/src/index.js
  example/cds-hooks-api-guide/src/prefetch-context/prefetch-context.js
  example/cds-hooks-api-guide/src/prefetch-context/util.js
  example/cds-hooks-api-guide/src/suggestions-links-fhir/suggestions-links-fhir.js
  example/cds-hooks-api-guide/src/suggestions-links-fhir/util.js
Labels: documentation, enhancement
