Repository flexpa/sero, pull requests merged in 2021-07, with the labels that each got.

#18 FHIR Client
  README.md
  package-lock.json
  package.json
  src/cds-hooks/index.test.ts
  src/client/index.test.ts
  src/client/index.ts
Labels: yolo

#27 GoodRx Example
  example/goodrx/README.md
  example/goodrx/api.ts
  example/goodrx/good-rx-compare-price.ts
  example/goodrx/index.ts
  src/cds-hooks/index.ts
  src/cds-hooks/routes.ts
  src/cds-hooks/util.ts
  src/http/index.ts
  test/cds-hooks/order-select.ts
Labels: documentation, enhancement

#42 Node 12.7+ package export resolution settings
  package.json
Labels: chore, enhancement

#54 ESM + CommonJS + Types exporting + Flat top level exports + Submodule exports
  jest.config.ts
  package-lock.json
  package.json
  src/cds-hooks/card.ts
  src/cds-hooks/index.ts
  src/cds-hooks/routes.ts
  src/cds-hooks/service.ts
  src/cds-hooks/suggestion.ts
  src/cds-hooks/util.ts
  src/client/index.ts
  src/config.ts
  src/index.ts
  src/rest/capabilities.ts
  src/rest/index.ts
  src/rest/routes/interactions.ts
  src/types/.DS_Store
  src/types/cds-hooks/index.d.ts
  src/types/index.d.ts
  src/types/smart/index.d.ts
  test/cds-hooks/appointment-book.ts
  test/cds-hooks/encounter-discharge.ts
  test/cds-hooks/encounter-start.ts
  test/cds-hooks/medication-prescribe.ts
  test/cds-hooks/order-review.ts
  test/cds-hooks/order-select.ts
  test/cds-hooks/order-sign.ts
  test/cds-hooks/patient-view.ts
  tsconfig.json
  tsconfig/base.json
  tsconfig/cjs.json
  tsconfig/esm.json
  tsconfig/test.json
  tsconfig/types.json
Labels: enhancement

#56 Common JS Fix
  package-lock.json
  package.json
  src/rest/store.ts
  tsconfig/base.json
  tsconfig/test.json
Labels: enhancement

#58 DaVinci CRD CDS Hooks example/service
  example/cds-hooks/better-patient-view.ts
  example/current-time/get-current-time.ts
  src/cds-hooks/service.ts
Labels: enhancement

#57 GoodRx Guide
  example/goodrx-cds-price-comparison/Dockerfile
  example/goodrx-cds-price-comparison/README.md
  example/goodrx-cds-price-comparison/package-lock.json
  example/goodrx-cds-price-comparison/package.json
  example/goodrx-cds-price-comparison/src/api.ts
  example/goodrx-cds-price-comparison/src/good-rx-compare-price.ts
  example/goodrx-cds-price-comparison/src/index.ts
  example/goodrx-cds-price-comparison/tsconfig.json
  example/goodrx/README.md
  example/goodrx/index.ts
Labels: documentation

#61 Get current time standalone example
  example/cds-hooks-api-guide/package-lock.json
  example/cds-hooks-api-guide/package.json
  example/cds-hooks-api-guide/src/current-time/current-time.js
  example/cds-hooks-api-guide/src/index.js
Labels: documentation
