Repository flexpa/sero, pull requests merged in 2021-09, with the labels that each got.

#77 CDS Hooks guide v2 - connectathon enhancements
  example/cds-hooks-api-guide/src/suggestions-links-fhir/data.js
  example/cds-hooks-api-guide/src/suggestions-links-fhir/suggestions-links-fhir.js
Labels: enhancement

#83 Feature/card typing
  src/cds-hooks/card.ts
Labels: bug

#85 GoodRx code reversion back to its pre-connectathon code
  example/goodrx-cds-price-comparison/src/good-rx-compare-price.ts
Labels: chore

#89 Remove the publish to Github Registry action that keeps failing
  .github/workflows/npm-publish.yml
Labels: chore

#91 Updating examples to match the new fastify plugin architecture
  example/cds-hooks-api-guide/package-lock.json
  example/cds-hooks-api-guide/package.json
  example/cds-hooks-api-guide/src/current-time/current-time.js
  example/cds-hooks-api-guide/src/index.js
  example/cds-hooks-api-guide/src/prefetch-context/prefetch-context.js
  example/cds-hooks-api-guide/src/suggestions-links-fhir/suggestions-links-fhir.js
  example/connectathon-cds-hooks/package-lock.json
  example/connectathon-cds-hooks/package.json
  example/connectathon-cds-hooks/src/index.js
  example/goodrx-cds-price-comparison/package-lock.json
  example/goodrx-cds-price-comparison/package.json
  example/goodrx-cds-price-comparison/src/good-rx-compare-price.ts
  example/goodrx-cds-price-comparison/src/index.ts
  example/humana-specialist-search/package-lock.json
  example/humana-specialist-search/package.json
Labels: chore
